sudo: false
language: python
services:
  - docker
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - env: TOX_ENV=py35
      python: 3.5

install:
  - pip install -U tox

script: travis_retry tox -e $TOX_ENV



